<a href="https://colab.research.google.com/github/rameshbabuatreyu/Machine-Learning/blob/master/NLP_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
import keras

In [0]:
from keras.datasets import imdb

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

In [0]:
vocab_size = 10000

In [0]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300


In [0]:

#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)
#y_train = pad_sequences(y_train, maxlen=maxlen)

In [0]:
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [0]:
#Creating the word index

word_to_index = imdb.get_word_index()
for (k,v) in word_to_index.items():
  word_to_index[k] = v + 3

index_to_word = {}
index_to_word[0] = "PAD"
index_to_word[1] = "START"
index_to_word[2] = "OOV"
for (k,v) in word_to_index.items():
  index_to_word[v] = k
for r in range(len(x_train)):
  for c in range(len(x_train[r])):
    idx=x_train[r][c]
    wrd=index_to_word[idx]
    print(wrd)
  print(" -> %d" % y_train[r])
print("\n")

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional
from keras.optimizers import Adam
from keras import backend
from keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau

In [20]:
model = Sequential()

In [21]:
# Embedding layer
model.add(
    Embedding(
        input_dim=1000,
        output_dim=100,
        weights=None,
        trainable=True))

In [22]:
# Recurrent layer
model.add(
    LSTM(
        64, return_sequences=False, dropout=0.1,
        recurrent_dropout=0.1))

# Fully connected layer
model.add(Dense(64, activation='sigmoid'))

# Dropout for regularization
model.add(Dropout(0.5))

# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(
    optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 100)         100000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                42240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 146,465
Trainable params: 

In [0]:
callback_reduce_lr = ReduceLROnPlateau(monitor='acc',
                                      factor=0.1,
                                      min_lr=1e-4,
                                      patience=0,
                                      verbose=2)

In [0]:
SEQUENCES = 50
TIME_STEPS = 100

In [0]:
import numpy as np

In [0]:

x_train = np.random.randint(1000, size=(SEQUENCES, TIME_STEPS), dtype='int32')

In [27]:
x_train

array([[  6, 232, 580, ..., 418, 454, 396],
       [ 23, 294,   2, ..., 966, 287, 850],
       [712, 740, 742, ..., 235,   9, 851],
       ...,
       [297,  77, 373, ..., 385, 105, 308],
       [823, 329,  14, ..., 849, 287, 109],
       [866, 417, 930, ..., 666, 867, 118]], dtype=int32)

In [0]:

y_train = np.random.rand(SEQUENCES)

In [29]:
y_train

array([0.00226467, 0.50906363, 0.68476934, 0.3406331 , 0.3689114 ,
       0.84121054, 0.71135972, 0.35584498, 0.63210539, 0.18971161,
       0.14706242, 0.49947805, 0.89312868, 0.89019369, 0.88824173,
       0.09943748, 0.164446  , 0.30138177, 0.71393166, 0.32644726,
       0.08453326, 0.92043457, 0.64358388, 0.5687583 , 0.16952611,
       0.86184004, 0.26419319, 0.09431606, 0.37194559, 0.14908337,
       0.41192438, 0.66495721, 0.951841  , 0.90685774, 0.35431635,
       0.11860218, 0.04230365, 0.55361985, 0.46490511, 0.04621051,
       0.32724255, 0.37350661, 0.51567418, 0.48424072, 0.23634623,
       0.88802908, 0.75546317, 0.60017009, 0.28939442, 0.73000836])

In [30]:

intialmodel = model.fit(x_train, y_train, epochs = 500, batch_size = 50,verbose=1,callbacks=[callback_reduce_lr])




Epoch 1/500





50/50 [==============================] - 1s 26ms/step - loss: 0.8824 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8681 - acc: 0.0000e+00

Epoch 00002: ReduceLROnPlateau reducing learning rate to 0.00010000000474974513.
Epoch 3/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8505 - acc: 0.0000e+00

Epoch 00003: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8239 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8600 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.9211 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8681 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8471 - acc: 0.0000e+00
Epoch 9/500
50/50 [==============================] - 0s 3ms

In [31]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:

#Save the model
model.save('/content/drive/My Drive/NLPModel.h5')

In [0]:
model = load_model('/content/drive/My Drive/NLPModel.h5')

In [35]:
model.fit(x_train, y_train, batch_size=50, epochs=500)

Epoch 1/500
50/50 [==============================] - 1s 16ms/step - loss: 0.5637 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5668 - acc: 0.0000e+00
Epoch 3/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5537 - acc: 0.0000e+00
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5428 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5706 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5536 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5665 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5633 - acc: 0.0000e+00
Epoch 9/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5518 - acc: 0.0000e+00
Epoch 10/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5617 - acc: 0.0000e+00
Epoch 11/500
50/50

In [37]:
print(model.evaluate(x_train, y_train, batch_size = 50))


50/50 [==============================] - 0s 657us/step
[0.5149780511856079, 0.0]


In [38]:
print('\nModel Performance: Log Loss and Accuracy on validation data')



Model Performance: Log Loss and Accuracy on validation data


In [0]:
print(model.evaluate(x_test, y_test, batch_size = 5))